# Generated by Django 2.0.6 on 2018-07-10 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0008_auto_20180710_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('article', models.ManyToManyField(related_name='article_post', to='article.ArticlesPost')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
