# Generated by Django 2.0.6 on 2018-07-14 05:04

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/article/avatar_thumbnail/'),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
