# Generated by Django 2.0.6 on 2018-07-15 02:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180714_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/course/avatar_thumbnail/'),
        ),
    ]
