# Generated by Django 2.0.6 on 2018-08-20 04:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180715_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/course/%Y%m%d'),
        ),
    ]
