# Generated by Django 2.0.6 on 2018-12-13 12:35

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180820_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('created',), 'verbose_name_plural': '教程'},
        ),
        migrations.AlterField(
            model_name='course',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/course/%Y%m%d', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='已完结'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
