# Generated by Django 2.0.6 on 2018-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20180703_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
