# Generated by Django 2.0.6 on 2018-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20180703_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
