# Generated by Django 2.0.6 on 2018-07-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_auto_20180709_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumcomment',
            old_name='album',
            new_name='photo',
        ),
    ]
