# Generated by Django 2.0.6 on 2018-07-10 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0015_auto_20180709_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_comments_reply_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
