# Generated by Django 2.0.6 on 2018-07-16 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('readbook', '0002_auto_20180715_1124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0016_albumcomment_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadBookCommnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readbook_comments', to='readbook.ReadBook')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.ReadBookCommnet')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readbook_comments_reply_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readbook_comments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
