# Generated by Django 2.0.6 on 2018-07-16 03:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('readbook', '0003_auto_20180716_1108'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0017_readbookcommnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadBookCommnet',
            new_name='ReadBookComment',
        ),
    ]
