# Generated by Django 2.0.6 on 2018-07-16 03:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readbook', '0003_auto_20180716_1108'),
        ('comments', '0018_auto_20180716_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadBookComment',
            new_name='ReadBookCommnet',
        ),
    ]
