# Generated by Django 2.0.6 on 2018-07-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0020_auto_20180716_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbookcomment',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readbookcomment',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readbookcomment',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readbookcomment',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
