# Generated by Django 2.0.6 on 2018-12-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0021_auto_20180716_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcomment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='albumcomment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='albumcomment',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.ArticlesPost', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.Comment', verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_reply_to', to=settings.AUTH_USER_MODEL, verbose_name='评论给'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='readbookcomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readbook_comments', to='readbook.ReadBook', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='readbookcomment',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='readbookcomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.ReadBookComment', verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='readbookcomment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readbook_comments_reply_to', to=settings.AUTH_USER_MODEL, verbose_name='评论给'),
        ),
        migrations.AlterField(
            model_name='readbookcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readbook_comments_user', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.DeleteModel(
            name='AlbumComment',
        ),
    ]
