# Generated by Django 2.0.6 on 2019-01-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0023_vlogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbookcomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='readbook.ReadBook', verbose_name='文章'),
        ),
    ]
