# Generated by Django 2.0.6 on 2019-01-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0025_auto_20190104_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
