# Generated by Django 2.0.6 on 2019-01-08 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0028_auto_20190108_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbookcomment',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='vlogcomment',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='正文'),
        ),
    ]
