# Generated by Django 2.0.6 on 2019-01-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0030_auto_20190121_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readbookcomment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='readbookcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='readbookcomment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='readbookcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vlogcomment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='vlogcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='vlogcomment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='vlogcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadBookComment',
        ),
        migrations.DeleteModel(
            name='VlogComment',
        ),
    ]
