# Generated by Django 2.0.6 on 2018-07-16 05:44

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='image/course/avatar_thumbnail/')),
            ],
        ),
    ]
