# Generated by Django 2.0.6 on 2018-07-16 06:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imagesource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesource',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='image/image_source/avatar_thumbnail/'),
        ),
    ]
