# Generated by Django 2.0.6 on 2018-08-20 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesource', '0002_auto_20180716_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesource',
            options={'ordering': ('-created',)},
        ),
    ]
