# Generated by Django 2.0.6 on 2018-08-20 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imagesource', '0003_auto_20180820_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesource',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
