# Generated by Django 2.0.6 on 2018-08-20 04:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imagesource', '0004_auto_20180820_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesource',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='image/image_source/%Y%m%d'),
        ),
    ]
