# Generated by Django 2.0.6 on 2018-12-13 12:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imagesource', '0005_auto_20180820_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesource',
            options={'ordering': ('-created',), 'verbose_name_plural': '图库'},
        ),
        migrations.AlterField(
            model_name='imagesource',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='image/image_source/%Y%m%d', verbose_name='图片'),
        ),
    ]
