# Generated by Django 2.0.6 on 2018-07-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='total_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
