# Generated by Django 2.0.6 on 2018-07-04 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180704_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescolumn',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
