# Generated by Django 2.0.6 on 2018-07-04 06:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('article', '0004_articlescolumn_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlespost',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='articlespost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
