# Generated by Django 2.0.6 on 2018-07-10 03:18

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180704_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='image/article/avatar_thumbnail/'),
        ),
    ]
