# Generated by Django 2.0.6 on 2018-07-10 03:29

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlespost_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/article/avatar_thumbnail/'),
        ),
    ]
