# Generated by Django 2.0.6 on 2018-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_articlespost_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespost',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='article', to='course.Course'),
        ),
    ]
