# Generated by Django 2.0.6 on 2018-07-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_article'),
        ('article', '0010_auto_20180710_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlespost',
            name='course',
        ),
        migrations.AddField(
            model_name='articlespost',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='course.Course'),
        ),
    ]
