# Generated by Django 2.0.6 on 2018-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20180710_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='course_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
