# Generated by Django 2.0.6 on 2018-08-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_remove_articlespost_total_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='course_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
