# Generated by Django 2.0.6 on 2018-12-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20180820_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescolumn',
            options={'verbose_name_plural': '栏目'},
        ),
        migrations.AlterModelOptions(
            name='articlespost',
            options={'ordering': ('-created',), 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='articlescolumn',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/article/%Y%m%d', verbose_name='标题图'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column', to='article.ArticlesColumn', verbose_name='栏目'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='course.Course', verbose_name='教程'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='course_sequence',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='教程序号'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='course_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='课程标题'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='url',
            field=models.URLField(blank=True, verbose_name='标题图url'),
        ),
    ]
