# Generated by Django 2.0.6 on 2019-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20181213_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespost',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
