# Generated by Django 2.0.6 on 2019-01-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20190128_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
