# Generated by Django 2.0.6 on 2019-02-12 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20190129_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespost',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column', to='article.ArticlesColumn', verbose_name='栏目'),
        ),
        migrations.AlterField(
            model_name='articlespost',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='course.Course', verbose_name='教程'),
        ),
    ]
