# Generated by Django 2.0.6 on 2019-03-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0002_auto_20181215_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='avatar_url',
            field=models.URLField(verbose_name='标题图链接'),
        ),
    ]
