# Generated by Django 2.0.6 on 2019-01-25 16:47

from django.db import migrations, models
import imagekit.models.fields
import userinfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=userinfo.models.user_directory_path, verbose_name='头像')),
            ],
        ),
    ]
