# Generated by Django 2.0.6 on 2019-01-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='avatar_thumbnail',
            new_name='avatar',
        ),
    ]
