# Generated by Django 2.0.6 on 2018-07-06 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('photographer', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('photo_time', models.TextField(blank=True)),
                ('camera', models.TextField(blank=True)),
                ('lens', models.TextField(blank=True)),
                ('focal_length', models.TextField(blank=True)),
                ('aperture', models.TextField(blank=True)),
                ('exposure_time', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='image/album/%Y%m%d')),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
