# Generated by Django 2.0.6 on 2018-07-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
