# Generated by Django 2.0.6 on 2018-07-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_total_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-created',)},
        ),
    ]
