# Generated by Django 2.0.6 on 2018-08-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180709_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
