# Generated by Django 2.0.6 on 2018-12-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20180808_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-created',), 'verbose_name_plural': '照片墙'},
        ),
        migrations.AlterField(
            model_name='album',
            name='aperture',
            field=models.TextField(blank=True, verbose_name='光圈'),
        ),
        migrations.AlterField(
            model_name='album',
            name='camera',
            field=models.TextField(blank=True, verbose_name='相机型号'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='album',
            name='exposure_time',
            field=models.TextField(blank=True, verbose_name='曝光时间'),
        ),
        migrations.AlterField(
            model_name='album',
            name='focal_length',
            field=models.TextField(blank=True, verbose_name='焦距'),
        ),
        migrations.AlterField(
            model_name='album',
            name='lens',
            field=models.TextField(blank=True, verbose_name='镜头型号'),
        ),
        migrations.AlterField(
            model_name='album',
            name='location',
            field=models.TextField(blank=True, verbose_name='拍摄地'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo_time',
            field=models.TextField(blank=True, verbose_name='拍摄时间'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photographer',
            field=models.TextField(blank=True, verbose_name='拍摄者'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL, verbose_name='发布员'),
        ),
    ]
