# Generated by Django 2.0.6 on 2019-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20181213_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='aperture',
        ),
        migrations.RemoveField(
            model_name='album',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='album',
            name='exposure_time',
        ),
        migrations.RemoveField(
            model_name='album',
            name='focal_length',
        ),
        migrations.RemoveField(
            model_name='album',
            name='lens',
        ),
        migrations.RemoveField(
            model_name='album',
            name='location',
        ),
        migrations.RemoveField(
            model_name='album',
            name='photo_time',
        ),
        migrations.RemoveField(
            model_name='album',
            name='photographer',
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/album/%Y%m%d'),
        ),
    ]
