# Generated by Django 2.0.6 on 2018-07-15 02:03

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_score', models.FloatField(blank=True)),
                ('practicality', models.PositiveIntegerField()),
                ('interesting', models.PositiveIntegerField()),
                ('readability', models.PositiveIntegerField()),
                ('professionalism', models.PositiveIntegerField()),
                ('binding_quality', models.PositiveIntegerField()),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/read_book/avatar_thumbnail/')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
