# Generated by Django 2.0.6 on 2018-07-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readbook',
            name='book_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readbook',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
