# Generated by Django 2.0.6 on 2018-08-20 04:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('readbook', '0004_remove_readbook_total_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbook',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/read_book/%Y%m%d'),
        ),
    ]
