# Generated by Django 2.0.6 on 2018-12-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('readbook', '0005_auto_20180820_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readbook',
            options={'ordering': ('-created',), 'verbose_name_plural': '读书'},
        ),
        migrations.AlterField(
            model_name='readbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_book_article', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/read_book/%Y%m%d', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='binding_quality',
            field=models.PositiveIntegerField(verbose_name='装订'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='book_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='页数'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='interesting',
            field=models.PositiveIntegerField(verbose_name='趣味性'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='practicality',
            field=models.PositiveIntegerField(verbose_name='实用度'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='professionalism',
            field=models.PositiveIntegerField(verbose_name='专业度'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='readability',
            field=models.PositiveIntegerField(verbose_name='易读性'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='total_score',
            field=models.FloatField(blank=True, verbose_name='总分数'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='writer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作者'),
        ),
    ]
