# Generated by Django 2.0.6 on 2019-03-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readbook', '0006_auto_20181213_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
            ],
            options={
                'verbose_name_plural': '栏目',
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
            ],
            options={
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
            ],
            options={
                'verbose_name_plural': '类型',
            },
        ),
        migrations.AlterModelOptions(
            name='readbook',
            options={'ordering': ('column', 'tag', 'type'), 'verbose_name_plural': '知识'},
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='avatar_thumbnail',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='binding_quality',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='body',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='book_page',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='interesting',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='practicality',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='price',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='professionalism',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='readability',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='writer',
        ),
        migrations.AddField(
            model_name='readbook',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='readbook',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readbook.BookColumn'),
        ),
        migrations.AddField(
            model_name='readbook',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readbook.BookTag'),
        ),
        migrations.AddField(
            model_name='readbook',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readbook.BookType'),
        ),
    ]
