# Generated by Django 2.0.6 on 2019-03-03 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readbook', '0007_auto_20190303_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='read_book_article', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
    ]
